# Generated by Django 6.0.5 on 2026-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
    ]
